/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import controlador.Controlador;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author fabricio
 */
public class VistaSolicitarCita extends javax.swing.JFrame {
    
    private Controlador controlador = new Controlador();

    /**
     * Creates new form VistaSolicitarCita
     */
    public VistaSolicitarCita() {
        
        initComponents();
        ArrayList<String> lista = controlador.verMascotas();
        String[] listavista = new String[lista.size()];
        
        for(int i=1; i<lista.size();i++){
            listavista[i] = lista.get(i);
        }
        this.jcbxMascota.setModel(new DefaultComboBoxModel(listavista));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblsolicitarCita = new javax.swing.JLabel();
        lbltipo = new javax.swing.JLabel();
        jcbxTipo = new javax.swing.JComboBox();
        jlblMascota = new javax.swing.JLabel();
        jcbxMascota = new javax.swing.JComboBox();
        jlblDoctor = new javax.swing.JLabel();
        jcbxDoctor = new javax.swing.JComboBox();
        jlblFecha = new javax.swing.JLabel();
        jbtnEnviar = new javax.swing.JButton();
        JBTNCancelar = new javax.swing.JButton();
        jtxfdia = new javax.swing.JTextField();
        jtxfmes = new javax.swing.JTextField();
        jtxfanio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblsolicitarCita.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        lblsolicitarCita.setForeground(new java.awt.Color(255, 51, 51));
        lblsolicitarCita.setText("SOLICITAR CITA");

        lbltipo.setText("TIPO:");

        jcbxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Consulta Externa", "Cirugia", "Urgencia" }));

        jlblMascota.setText("MASCOTA:");

        jcbxMascota.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        jcbxMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxMascotaActionPerformed(evt);
            }
        });

        jlblDoctor.setText("DOCTOR:");

        jcbxDoctor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Carlos" }));

        jlblFecha.setText("FECHA:");

        jbtnEnviar.setText("ENVIAR");
        jbtnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEnviarActionPerformed(evt);
            }
        });

        JBTNCancelar.setText("CANCELAR");
        JBTNCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNCancelarActionPerformed(evt);
            }
        });

        jtxfdia.setText("dd");
        jtxfdia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxfdiaActionPerformed(evt);
            }
        });

        jtxfmes.setText("mm");

        jtxfanio.setText("aaaa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(lblsolicitarCita)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltipo)
                            .addComponent(jlblMascota)
                            .addComponent(jlblDoctor)
                            .addComponent(jlblFecha))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbxMascota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbxDoctor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jtxfdia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtxfmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxfanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jbtnEnviar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBTNCancelar)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblsolicitarCita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltipo)
                    .addComponent(jcbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblMascota)
                    .addComponent(jcbxMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblDoctor)
                    .addComponent(jcbxDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblFecha)
                    .addComponent(jtxfdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxfmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxfanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnEnviar)
                    .addComponent(JBTNCancelar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTNCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_JBTNCancelarActionPerformed

    private void jcbxMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxMascotaActionPerformed
        
    }//GEN-LAST:event_jcbxMascotaActionPerformed

    private void jtxfdiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxfdiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxfdiaActionPerformed

    private void jbtnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEnviarActionPerformed
        String tipo = this.jcbxTipo.getSelectedItem().toString();
        String mascota = this.jcbxMascota.getSelectedItem().toString();
        String doctor = this.jcbxDoctor.getSelectedItem().toString();
        String fecha = this.jtxfdia.getText()+"/"+this.jtxfmes.getText()+"/"+this.jtxfanio.getText();
        
        if(controlador.asignarCita(fecha, doctor, tipo, mascota)){
            JOptionPane.showMessageDialog(null, "Cita asignada");
        }
        else{
            JOptionPane.showMessageDialog(null, "Error en los datos");
        }
    }//GEN-LAST:event_jbtnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaSolicitarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaSolicitarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaSolicitarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaSolicitarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaSolicitarCita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTNCancelar;
    private javax.swing.JButton jbtnEnviar;
    private javax.swing.JComboBox jcbxDoctor;
    private javax.swing.JComboBox jcbxMascota;
    private javax.swing.JComboBox jcbxTipo;
    private javax.swing.JLabel jlblDoctor;
    private javax.swing.JLabel jlblFecha;
    private javax.swing.JLabel jlblMascota;
    private javax.swing.JTextField jtxfanio;
    private javax.swing.JTextField jtxfdia;
    private javax.swing.JTextField jtxfmes;
    private javax.swing.JLabel lblsolicitarCita;
    private javax.swing.JLabel lbltipo;
    // End of variables declaration//GEN-END:variables
}
